### ISSUE TITLE
Ive never used this kind of Documenation

### ISSUE THREAD

**Issue by CoderGuyTedd** [CraterCrash/godot-orchestrator-docs#69]
Ive never used this kind of Documenation, how can I contribute?

**Comment by Naros** [comment]
Hi @CoderGuyTedd so our documentation uses Docusaurus, which requires `npm`.

You will use `npm run serve` in a terminal window to start the web server, automatically opening a browser window to `localhost:3000/orchestrator`. From here you can view the content as you edit it in real-time.

The layout of the documentation is quite straightforward:

* `/docs` is the base directory for all the documentation.
* `/i18n/<locale>/` is the translation of the documentation for that locale.
* `/src` are Docusaurus customizations, most can ignore this
* `/static/img` is where all images to be shown in the documentation go.

In the `/docs` folder, each main file is written in Markdown, `.md` files. You'll find at the top of most markdown files there are some key/value pairs in between two `---` rows, which is called FrontMatter attributes.  These control the static generation for those pages.

If you have any other questions, let us know or read up on Docusuarus at https://docusuarus.io

**Comment by CoderGuyTedd** [comment]
Ok thanks
